monolog:
    channels:
        - access
        - deprecation

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!access"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            access:
                type: stream
                path: "%kernel.logs_dir%/access.log"
                level: debug
                channels: ["access"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: "%kernel.logs_dir%/main.log"
                level: debug
                channels: ["!event", "!access"]
                max_files: 14
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            access:
                type: stream
                path: "%kernel.logs_dir%/access.log"
                level: debug
                channels: ["access"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
